### ISSUE TITLE
Not able to import RandomSampler, Getting error "ImportError: cannot import name 'RandomSampler'"?

### ISSUE THREAD

**Issue by Linkyx** [huggingface/pytorch-pretrained-BERT#345]
Not able to import RandomSampler, Getting error "ImportError: cannot import name 'RandomSampler'"? Did I get a wrong torch version?

**Comment by Linkyx** [comment]
The requirements.txt needs torch>=0.4.1 .    i've got the  version 0.5.0, how can i solve it? thank you~

**Comment by ZWado** [comment]
how do you fix this issue?

**Comment by Linkyx** [comment]
> how do you fix this issue?

try to update your torch version，i found it didn't work in torch 4.0.0, try  "torch >=4.0.1"
